trigger:
- main
 
pool:
  vmImage: 'ubuntu-latest'
 
variables:
  SF_CLIENT_ID: $(SF_CLIENT_ID)
  SF_CLIENT_SECRET: $(SF_CLIENT_SECRET)
  SF_USERNAME: $(SF_USERNAME)
  SF_PASSWORD: $(SF_PASSWORD)
  SF_SECURITY_TOKEN: $(SF_SECURITY_TOKEN)
  SF_INSTANCE_URL: https://login.salesforce.com
 
steps:
- script: |
    npm install -g sfdx-cli
    sfdx --version
    echo "Authenticating to Salesforce..."
    sfdx force:auth:password:grant \
      --clientid $(SF_CLIENT_ID) \
      --clientsecret $(SF_CLIENT_SECRET) \
      --username $(SF_USERNAME) \
      --password "$(SF_PASSWORD)$(SF_SECURITY_TOKEN)" \
      --instanceurl $(SF_INSTANCE_URL) \
      --setdefaultusername
    echo "Displaying Salesforce Org info..."
    sfdx force:org:display -u $(SF_USERNAME)
  displayName: 'Authenticate to Salesforce and Display Org Info'